/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Audit {
  'id' : bigint,
  'businessId' : bigint,
  'userId' : bigint,
  'createdAt' : Timestamp,
  'instagramScore' : bigint,
  'leadScore' : bigint,
  'websiteScore' : bigint,
  'whatsappScore' : bigint,
  'googleScore' : bigint,
}
export interface Business {
  'id' : bigint,
  'city' : string,
  'userId' : bigint,
  'instagram' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'whatsapp' : string,
  'description' : string,
  'category' : string,
  'googleMaps' : string,
}
export interface Contact {
  'id' : bigint,
  'service' : string,
  'country' : string,
  'ownerName' : string,
  'city' : string,
  'createdAt' : Timestamp,
  'businessName' : string,
  'whatsapp' : string,
  'budget' : string,
}
export interface CreateAuditInput {
  'businessId' : bigint,
  'userId' : bigint,
  'instagramScore' : bigint,
  'leadScore' : bigint,
  'websiteScore' : bigint,
  'whatsappScore' : bigint,
  'googleScore' : bigint,
}
export interface CreateBusinessInput {
  'city' : string,
  'userId' : bigint,
  'instagram' : string,
  'name' : string,
  'whatsapp' : string,
  'description' : string,
  'category' : string,
  'googleMaps' : string,
}
export interface CreateContactInput {
  'service' : string,
  'country' : string,
  'ownerName' : string,
  'city' : string,
  'businessName' : string,
  'whatsapp' : string,
  'budget' : string,
}
export interface CreateInvoiceInput {
  'status' : InvoiceStatus,
  'date' : Timestamp,
  'subscriptionId' : bigint,
  'currency' : string,
  'amount' : bigint,
}
export interface CreateLeadInput {
  'leadType' : LeadType,
  'source' : LeadSource,
  'businessId' : bigint,
}
export interface CreateSubscriptionInput {
  'endDate' : Timestamp,
  'stripeSubscriptionId' : string,
  'userId' : bigint,
  'plan' : Plan,
  'startDate' : Timestamp,
}
export interface CreateUserInput {
  'principal' : Principal,
  'country' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface Invoice {
  'id' : bigint,
  'status' : InvoiceStatus,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'subscriptionId' : bigint,
  'currency' : string,
  'amount' : bigint,
}
export type InvoiceStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface LeadPublic {
  'id' : bigint,
  'status' : LeadStatus,
  'leadType' : LeadType,
  'source' : LeadSource,
  'businessId' : bigint,
  'createdAt' : Timestamp,
}
export type LeadSource = { 'instagram' : null } |
  { 'whatsapp' : null } |
  { 'google' : null } |
  { 'website' : null };
export type LeadStatus = { 'new' : null } |
  { 'contacted' : null } |
  { 'converted' : null };
export type LeadType = { 'call' : null } |
  { 'inquiry' : null } |
  { 'booking' : null };
export type Plan = { 'growth' : null } |
  { 'starter' : null } |
  { 'premium' : null } |
  { 'none' : null };
export interface SubscriptionPublic {
  'id' : bigint,
  'status' : SubscriptionStatus,
  'endDate' : Timestamp,
  'stripeSubscriptionId' : string,
  'userId' : bigint,
  'createdAt' : Timestamp,
  'plan' : Plan,
  'startDate' : Timestamp,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'canceled' : null } |
  { 'expired' : null };
export type Timestamp = bigint;
export interface UserPublic {
  'id' : bigint,
  'principal' : Principal,
  'country' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'plan' : Plan,
  'role' : UserRole,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export interface _SERVICE {
  'createAudit' : ActorMethod<[CreateAuditInput], Audit>,
  'createBusiness' : ActorMethod<[CreateBusinessInput], Business>,
  'createContact' : ActorMethod<[CreateContactInput], Contact>,
  'createInvoice' : ActorMethod<[CreateInvoiceInput], Invoice>,
  'createLead' : ActorMethod<[CreateLeadInput], LeadPublic>,
  'createSubscription' : ActorMethod<
    [CreateSubscriptionInput],
    SubscriptionPublic
  >,
  'createUser' : ActorMethod<[CreateUserInput], UserPublic>,
  'getAuditsByUser' : ActorMethod<[bigint], Array<Audit>>,
  'getBusiness' : ActorMethod<[bigint], [] | [Business]>,
  'getBusinessByUser' : ActorMethod<[bigint], [] | [Business]>,
  'getInvoicesByUser' : ActorMethod<[bigint], Array<Invoice>>,
  'getLeadsByBusiness' : ActorMethod<[bigint], Array<LeadPublic>>,
  'getSubscriptionByUser' : ActorMethod<[bigint], [] | [SubscriptionPublic]>,
  'getUser' : ActorMethod<[bigint], [] | [UserPublic]>,
  'listContacts' : ActorMethod<[], Array<Contact>>,
  'listLeads' : ActorMethod<[], Array<LeadPublic>>,
  'listUsers' : ActorMethod<[], Array<UserPublic>>,
  'updateSubscription' : ActorMethod<[bigint, SubscriptionStatus], boolean>,
  'updateUser' : ActorMethod<[bigint, string, string, string, string], boolean>,
  'updateUserRole' : ActorMethod<[bigint, UserRole], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];