/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateAuditInput = IDL.Record({
  'businessId' : IDL.Nat,
  'userId' : IDL.Nat,
  'instagramScore' : IDL.Nat,
  'leadScore' : IDL.Nat,
  'websiteScore' : IDL.Nat,
  'whatsappScore' : IDL.Nat,
  'googleScore' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const Audit = IDL.Record({
  'id' : IDL.Nat,
  'businessId' : IDL.Nat,
  'userId' : IDL.Nat,
  'createdAt' : Timestamp,
  'instagramScore' : IDL.Nat,
  'leadScore' : IDL.Nat,
  'websiteScore' : IDL.Nat,
  'whatsappScore' : IDL.Nat,
  'googleScore' : IDL.Nat,
});
export const CreateBusinessInput = IDL.Record({
  'city' : IDL.Text,
  'userId' : IDL.Nat,
  'instagram' : IDL.Text,
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'googleMaps' : IDL.Text,
});
export const Business = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'userId' : IDL.Nat,
  'instagram' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'whatsapp' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'googleMaps' : IDL.Text,
});
export const CreateContactInput = IDL.Record({
  'service' : IDL.Text,
  'country' : IDL.Text,
  'ownerName' : IDL.Text,
  'city' : IDL.Text,
  'businessName' : IDL.Text,
  'whatsapp' : IDL.Text,
  'budget' : IDL.Text,
});
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'country' : IDL.Text,
  'ownerName' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : Timestamp,
  'businessName' : IDL.Text,
  'whatsapp' : IDL.Text,
  'budget' : IDL.Text,
});
export const InvoiceStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const CreateInvoiceInput = IDL.Record({
  'status' : InvoiceStatus,
  'date' : Timestamp,
  'subscriptionId' : IDL.Nat,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'status' : InvoiceStatus,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'subscriptionId' : IDL.Nat,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
});
export const LeadType = IDL.Variant({
  'call' : IDL.Null,
  'inquiry' : IDL.Null,
  'booking' : IDL.Null,
});
export const LeadSource = IDL.Variant({
  'instagram' : IDL.Null,
  'whatsapp' : IDL.Null,
  'google' : IDL.Null,
  'website' : IDL.Null,
});
export const CreateLeadInput = IDL.Record({
  'leadType' : LeadType,
  'source' : LeadSource,
  'businessId' : IDL.Nat,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'contacted' : IDL.Null,
  'converted' : IDL.Null,
});
export const LeadPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeadStatus,
  'leadType' : LeadType,
  'source' : LeadSource,
  'businessId' : IDL.Nat,
  'createdAt' : Timestamp,
});
export const Plan = IDL.Variant({
  'growth' : IDL.Null,
  'starter' : IDL.Null,
  'premium' : IDL.Null,
  'none' : IDL.Null,
});
export const CreateSubscriptionInput = IDL.Record({
  'endDate' : Timestamp,
  'stripeSubscriptionId' : IDL.Text,
  'userId' : IDL.Nat,
  'plan' : Plan,
  'startDate' : Timestamp,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'canceled' : IDL.Null,
  'expired' : IDL.Null,
});
export const SubscriptionPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : SubscriptionStatus,
  'endDate' : Timestamp,
  'stripeSubscriptionId' : IDL.Text,
  'userId' : IDL.Nat,
  'createdAt' : Timestamp,
  'plan' : Plan,
  'startDate' : Timestamp,
});
export const CreateUserInput = IDL.Record({
  'principal' : IDL.Principal,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserPublic = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Principal,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'plan' : Plan,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'createAudit' : IDL.Func([CreateAuditInput], [Audit], []),
  'createBusiness' : IDL.Func([CreateBusinessInput], [Business], []),
  'createContact' : IDL.Func([CreateContactInput], [Contact], []),
  'createInvoice' : IDL.Func([CreateInvoiceInput], [Invoice], []),
  'createLead' : IDL.Func([CreateLeadInput], [LeadPublic], []),
  'createSubscription' : IDL.Func(
      [CreateSubscriptionInput],
      [SubscriptionPublic],
      [],
    ),
  'createUser' : IDL.Func([CreateUserInput], [UserPublic], []),
  'getAuditsByUser' : IDL.Func([IDL.Nat], [IDL.Vec(Audit)], ['query']),
  'getBusiness' : IDL.Func([IDL.Nat], [IDL.Opt(Business)], ['query']),
  'getBusinessByUser' : IDL.Func([IDL.Nat], [IDL.Opt(Business)], ['query']),
  'getInvoicesByUser' : IDL.Func([IDL.Nat], [IDL.Vec(Invoice)], ['query']),
  'getLeadsByBusiness' : IDL.Func([IDL.Nat], [IDL.Vec(LeadPublic)], ['query']),
  'getSubscriptionByUser' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SubscriptionPublic)],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(UserPublic)], ['query']),
  'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'listLeads' : IDL.Func([], [IDL.Vec(LeadPublic)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
  'updateSubscription' : IDL.Func(
      [IDL.Nat, SubscriptionStatus],
      [IDL.Bool],
      [],
    ),
  'updateUser' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateUserRole' : IDL.Func([IDL.Nat, UserRole], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateAuditInput = IDL.Record({
    'businessId' : IDL.Nat,
    'userId' : IDL.Nat,
    'instagramScore' : IDL.Nat,
    'leadScore' : IDL.Nat,
    'websiteScore' : IDL.Nat,
    'whatsappScore' : IDL.Nat,
    'googleScore' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const Audit = IDL.Record({
    'id' : IDL.Nat,
    'businessId' : IDL.Nat,
    'userId' : IDL.Nat,
    'createdAt' : Timestamp,
    'instagramScore' : IDL.Nat,
    'leadScore' : IDL.Nat,
    'websiteScore' : IDL.Nat,
    'whatsappScore' : IDL.Nat,
    'googleScore' : IDL.Nat,
  });
  const CreateBusinessInput = IDL.Record({
    'city' : IDL.Text,
    'userId' : IDL.Nat,
    'instagram' : IDL.Text,
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'googleMaps' : IDL.Text,
  });
  const Business = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'userId' : IDL.Nat,
    'instagram' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'whatsapp' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'googleMaps' : IDL.Text,
  });
  const CreateContactInput = IDL.Record({
    'service' : IDL.Text,
    'country' : IDL.Text,
    'ownerName' : IDL.Text,
    'city' : IDL.Text,
    'businessName' : IDL.Text,
    'whatsapp' : IDL.Text,
    'budget' : IDL.Text,
  });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'country' : IDL.Text,
    'ownerName' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : Timestamp,
    'businessName' : IDL.Text,
    'whatsapp' : IDL.Text,
    'budget' : IDL.Text,
  });
  const InvoiceStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const CreateInvoiceInput = IDL.Record({
    'status' : InvoiceStatus,
    'date' : Timestamp,
    'subscriptionId' : IDL.Nat,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'status' : InvoiceStatus,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'subscriptionId' : IDL.Nat,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const LeadType = IDL.Variant({
    'call' : IDL.Null,
    'inquiry' : IDL.Null,
    'booking' : IDL.Null,
  });
  const LeadSource = IDL.Variant({
    'instagram' : IDL.Null,
    'whatsapp' : IDL.Null,
    'google' : IDL.Null,
    'website' : IDL.Null,
  });
  const CreateLeadInput = IDL.Record({
    'leadType' : LeadType,
    'source' : LeadSource,
    'businessId' : IDL.Nat,
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'contacted' : IDL.Null,
    'converted' : IDL.Null,
  });
  const LeadPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeadStatus,
    'leadType' : LeadType,
    'source' : LeadSource,
    'businessId' : IDL.Nat,
    'createdAt' : Timestamp,
  });
  const Plan = IDL.Variant({
    'growth' : IDL.Null,
    'starter' : IDL.Null,
    'premium' : IDL.Null,
    'none' : IDL.Null,
  });
  const CreateSubscriptionInput = IDL.Record({
    'endDate' : Timestamp,
    'stripeSubscriptionId' : IDL.Text,
    'userId' : IDL.Nat,
    'plan' : Plan,
    'startDate' : Timestamp,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'canceled' : IDL.Null,
    'expired' : IDL.Null,
  });
  const SubscriptionPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : SubscriptionStatus,
    'endDate' : Timestamp,
    'stripeSubscriptionId' : IDL.Text,
    'userId' : IDL.Nat,
    'createdAt' : Timestamp,
    'plan' : Plan,
    'startDate' : Timestamp,
  });
  const CreateUserInput = IDL.Record({
    'principal' : IDL.Principal,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserPublic = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Principal,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'plan' : Plan,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'createAudit' : IDL.Func([CreateAuditInput], [Audit], []),
    'createBusiness' : IDL.Func([CreateBusinessInput], [Business], []),
    'createContact' : IDL.Func([CreateContactInput], [Contact], []),
    'createInvoice' : IDL.Func([CreateInvoiceInput], [Invoice], []),
    'createLead' : IDL.Func([CreateLeadInput], [LeadPublic], []),
    'createSubscription' : IDL.Func(
        [CreateSubscriptionInput],
        [SubscriptionPublic],
        [],
      ),
    'createUser' : IDL.Func([CreateUserInput], [UserPublic], []),
    'getAuditsByUser' : IDL.Func([IDL.Nat], [IDL.Vec(Audit)], ['query']),
    'getBusiness' : IDL.Func([IDL.Nat], [IDL.Opt(Business)], ['query']),
    'getBusinessByUser' : IDL.Func([IDL.Nat], [IDL.Opt(Business)], ['query']),
    'getInvoicesByUser' : IDL.Func([IDL.Nat], [IDL.Vec(Invoice)], ['query']),
    'getLeadsByBusiness' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeadPublic)],
        ['query'],
      ),
    'getSubscriptionByUser' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SubscriptionPublic)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(UserPublic)], ['query']),
    'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'listLeads' : IDL.Func([], [IDL.Vec(LeadPublic)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
    'updateSubscription' : IDL.Func(
        [IDL.Nat, SubscriptionStatus],
        [IDL.Bool],
        [],
      ),
    'updateUser' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Nat, UserRole], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };