/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface UserPublic {
    id: bigint;
    principal: Principal;
    country: string;
    name: string;
    createdAt: Timestamp;
    plan: Plan;
    role: UserRole;
    email: string;
    phone: string;
}
export interface LeadPublic {
    id: bigint;
    status: LeadStatus;
    leadType: LeadType;
    source: LeadSource;
    businessId: bigint;
    createdAt: Timestamp;
}
export interface CreateUserInput {
    principal: Principal;
    country: string;
    name: string;
    email: string;
    phone: string;
}
export interface CreateLeadInput {
    leadType: LeadType;
    source: LeadSource;
    businessId: bigint;
}
export interface CreateInvoiceInput {
    status: InvoiceStatus;
    date: Timestamp;
    subscriptionId: bigint;
    currency: string;
    amount: bigint;
}
export interface Invoice {
    id: bigint;
    status: InvoiceStatus;
    date: Timestamp;
    createdAt: Timestamp;
    subscriptionId: bigint;
    currency: string;
    amount: bigint;
}
export interface Contact {
    id: bigint;
    service: string;
    country: string;
    ownerName: string;
    city: string;
    createdAt: Timestamp;
    businessName: string;
    whatsapp: string;
    budget: string;
}
export interface Business {
    id: bigint;
    city: string;
    userId: bigint;
    instagram: string;
    name: string;
    createdAt: Timestamp;
    whatsapp: string;
    description: string;
    category: string;
    googleMaps: string;
}
export interface CreateBusinessInput {
    city: string;
    userId: bigint;
    instagram: string;
    name: string;
    whatsapp: string;
    description: string;
    category: string;
    googleMaps: string;
}
export interface CreateContactInput {
    service: string;
    country: string;
    ownerName: string;
    city: string;
    businessName: string;
    whatsapp: string;
    budget: string;
}
export interface CreateAuditInput {
    businessId: bigint;
    userId: bigint;
    instagramScore: bigint;
    leadScore: bigint;
    websiteScore: bigint;
    whatsappScore: bigint;
    googleScore: bigint;
}
export interface CreateSubscriptionInput {
    endDate: Timestamp;
    stripeSubscriptionId: string;
    userId: bigint;
    plan: Plan;
    startDate: Timestamp;
}
export interface SubscriptionPublic {
    id: bigint;
    status: SubscriptionStatus;
    endDate: Timestamp;
    stripeSubscriptionId: string;
    userId: bigint;
    createdAt: Timestamp;
    plan: Plan;
    startDate: Timestamp;
}
export interface Audit {
    id: bigint;
    businessId: bigint;
    userId: bigint;
    createdAt: Timestamp;
    instagramScore: bigint;
    leadScore: bigint;
    websiteScore: bigint;
    whatsappScore: bigint;
    googleScore: bigint;
}
export enum InvoiceStatus {
    pending = "pending",
    paid = "paid",
    failed = "failed"
}
export enum LeadSource {
    instagram = "instagram",
    whatsapp = "whatsapp",
    google = "google",
    website = "website"
}
export enum LeadStatus {
    new_ = "new",
    contacted = "contacted",
    converted = "converted"
}
export enum LeadType {
    call = "call",
    inquiry = "inquiry",
    booking = "booking"
}
export enum Plan {
    growth = "growth",
    starter = "starter",
    premium = "premium",
    none = "none"
}
export enum SubscriptionStatus {
    active = "active",
    canceled = "canceled",
    expired = "expired"
}
export enum UserRole {
    admin = "admin",
    user = "user"
}
export interface backendInterface {
    createAudit(input: CreateAuditInput): Promise<Audit>;
    createBusiness(input: CreateBusinessInput): Promise<Business>;
    createContact(input: CreateContactInput): Promise<Contact>;
    createInvoice(input: CreateInvoiceInput): Promise<Invoice>;
    createLead(input: CreateLeadInput): Promise<LeadPublic>;
    createSubscription(input: CreateSubscriptionInput): Promise<SubscriptionPublic>;
    createUser(input: CreateUserInput): Promise<UserPublic>;
    getAuditsByUser(userId: bigint): Promise<Array<Audit>>;
    getBusiness(id: bigint): Promise<Business | null>;
    getBusinessByUser(userId: bigint): Promise<Business | null>;
    getInvoicesByUser(userId: bigint): Promise<Array<Invoice>>;
    getLeadsByBusiness(businessId: bigint): Promise<Array<LeadPublic>>;
    getSubscriptionByUser(userId: bigint): Promise<SubscriptionPublic | null>;
    getUser(id: bigint): Promise<UserPublic | null>;
    listContacts(): Promise<Array<Contact>>;
    listLeads(): Promise<Array<LeadPublic>>;
    listUsers(): Promise<Array<UserPublic>>;
    updateSubscription(id: bigint, status: SubscriptionStatus): Promise<boolean>;
    updateUser(id: bigint, name: string, email: string, phone: string, country: string): Promise<boolean>;
    updateUserRole(id: bigint, role: UserRole): Promise<boolean>;
}
import type { Business as _Business, CreateInvoiceInput as _CreateInvoiceInput, CreateLeadInput as _CreateLeadInput, CreateSubscriptionInput as _CreateSubscriptionInput, Invoice as _Invoice, InvoiceStatus as _InvoiceStatus, LeadPublic as _LeadPublic, LeadSource as _LeadSource, LeadStatus as _LeadStatus, LeadType as _LeadType, Plan as _Plan, SubscriptionPublic as _SubscriptionPublic, SubscriptionStatus as _SubscriptionStatus, Timestamp as _Timestamp, UserPublic as _UserPublic, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAudit(arg0: CreateAuditInput): Promise<Audit> {
        if (this.processError) {
            try {
                const result = await this.actor.createAudit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAudit(arg0);
            return result;
        }
    }
    async createBusiness(arg0: CreateBusinessInput): Promise<Business> {
        if (this.processError) {
            try {
                const result = await this.actor.createBusiness(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBusiness(arg0);
            return result;
        }
    }
    async createContact(arg0: CreateContactInput): Promise<Contact> {
        if (this.processError) {
            try {
                const result = await this.actor.createContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContact(arg0);
            return result;
        }
    }
    async createInvoice(arg0: CreateInvoiceInput): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_CreateInvoiceInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Invoice_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_CreateInvoiceInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Invoice_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLead(arg0: CreateLeadInput): Promise<LeadPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(to_candid_CreateLeadInput_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_LeadPublic_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(to_candid_CreateLeadInput_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_LeadPublic_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSubscription(arg0: CreateSubscriptionInput): Promise<SubscriptionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscription(to_candid_CreateSubscriptionInput_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SubscriptionPublic_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscription(to_candid_CreateSubscriptionInput_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SubscriptionPublic_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: CreateUserInput): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0);
                return from_candid_UserPublic_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0);
            return from_candid_UserPublic_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditsByUser(arg0: bigint): Promise<Array<Audit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditsByUser(arg0);
            return result;
        }
    }
    async getBusiness(arg0: bigint): Promise<Business | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusiness(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusiness(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusinessByUser(arg0: bigint): Promise<Business | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessByUser(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessByUser(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByUser(arg0: bigint): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByUser(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByUser(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByBusiness(arg0: bigint): Promise<Array<LeadPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByBusiness(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByBusiness(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionByUser(arg0: bigint): Promise<SubscriptionPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionByUser(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionByUser(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: bigint): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContacts();
            return result;
        }
    }
    async listLeads(): Promise<Array<LeadPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeads();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeads();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSubscription(arg0: bigint, arg1: SubscriptionStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscription(arg0, to_candid_SubscriptionStatus_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscription(arg0, to_candid_SubscriptionStatus_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUser(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateUserRole(arg0: bigint, arg1: UserRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n45(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n45(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_InvoiceStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_LeadPublic_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadPublic): LeadPublic {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_LeadSource_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadSource): LeadSource {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_LeadType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadType): LeadType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Plan_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Plan): Plan {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPublic_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPublic): SubscriptionPublic {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Business]): Business | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionPublic]): SubscriptionPublic | null {
    return value.length === 0 ? null : from_candid_SubscriptionPublic_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LeadStatus;
    leadType: _LeadType;
    source: _LeadSource;
    businessId: bigint;
    createdAt: _Timestamp;
}): {
    id: bigint;
    status: LeadStatus;
    leadType: LeadType;
    source: LeadSource;
    businessId: bigint;
    createdAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n17(_uploadFile, _downloadFile, value.status),
        leadType: from_candid_LeadType_n19(_uploadFile, _downloadFile, value.leadType),
        source: from_candid_LeadSource_n21(_uploadFile, _downloadFile, value.source),
        businessId: value.businessId,
        createdAt: value.createdAt
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SubscriptionStatus;
    endDate: _Timestamp;
    stripeSubscriptionId: string;
    userId: bigint;
    createdAt: _Timestamp;
    plan: _Plan;
    startDate: _Timestamp;
}): {
    id: bigint;
    status: SubscriptionStatus;
    endDate: Timestamp;
    stripeSubscriptionId: string;
    userId: bigint;
    createdAt: Timestamp;
    plan: Plan;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_SubscriptionStatus_n29(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        stripeSubscriptionId: value.stripeSubscriptionId,
        userId: value.userId,
        createdAt: value.createdAt,
        plan: from_candid_Plan_n31(_uploadFile, _downloadFile, value.plan),
        startDate: value.startDate
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    principal: Principal;
    country: string;
    name: string;
    createdAt: _Timestamp;
    plan: _Plan;
    role: _UserRole;
    email: string;
    phone: string;
}): {
    id: bigint;
    principal: Principal;
    country: string;
    name: string;
    createdAt: Timestamp;
    plan: Plan;
    role: UserRole;
    email: string;
    phone: string;
} {
    return {
        id: value.id,
        principal: value.principal,
        country: value.country,
        name: value.name,
        createdAt: value.createdAt,
        plan: from_candid_Plan_n31(_uploadFile, _downloadFile, value.plan),
        role: from_candid_UserRole_n35(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InvoiceStatus;
    date: _Timestamp;
    createdAt: _Timestamp;
    subscriptionId: bigint;
    currency: string;
    amount: bigint;
}): {
    id: bigint;
    status: InvoiceStatus;
    date: Timestamp;
    createdAt: Timestamp;
    subscriptionId: bigint;
    currency: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_InvoiceStatus_n7(_uploadFile, _downloadFile, value.status),
        date: value.date,
        createdAt: value.createdAt,
        subscriptionId: value.subscriptionId,
        currency: value.currency,
        amount: value.amount
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    contacted: null;
} | {
    converted: null;
}): LeadStatus {
    return "new" in value ? LeadStatus.new : "contacted" in value ? LeadStatus.contacted : "converted" in value ? LeadStatus.converted : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    call: null;
} | {
    inquiry: null;
} | {
    booking: null;
}): LeadType {
    return "call" in value ? LeadType.call : "inquiry" in value ? LeadType.inquiry : "booking" in value ? LeadType.booking : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    instagram: null;
} | {
    whatsapp: null;
} | {
    google: null;
} | {
    website: null;
}): LeadSource {
    return "instagram" in value ? LeadSource.instagram : "whatsapp" in value ? LeadSource.whatsapp : "google" in value ? LeadSource.google : "website" in value ? LeadSource.website : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    canceled: null;
} | {
    expired: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "canceled" in value ? SubscriptionStatus.canceled : "expired" in value ? SubscriptionStatus.expired : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    growth: null;
} | {
    starter: null;
} | {
    premium: null;
} | {
    none: null;
}): Plan {
    return "growth" in value ? Plan.growth : "starter" in value ? Plan.starter : "premium" in value ? Plan.premium : "none" in value ? Plan.none : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
}): InvoiceStatus {
    return "pending" in value ? InvoiceStatus.pending : "paid" in value ? InvoiceStatus.paid : "failed" in value ? InvoiceStatus.failed : value;
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeadPublic>): Array<LeadPublic> {
    return value.map((x)=>from_candid_LeadPublic_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserPublic>): Array<UserPublic> {
    return value.map((x)=>from_candid_UserPublic_n33(_uploadFile, _downloadFile, x));
}
function to_candid_CreateInvoiceInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateInvoiceInput): _CreateInvoiceInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateLeadInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLeadInput): _CreateLeadInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_CreateSubscriptionInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateSubscriptionInput): _CreateSubscriptionInput {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LeadSource_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadSource): _LeadSource {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_LeadType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadType): _LeadType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Plan_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Plan): _Plan {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leadType: LeadType;
    source: LeadSource;
    businessId: bigint;
}): {
    leadType: _LeadType;
    source: _LeadSource;
    businessId: bigint;
} {
    return {
        leadType: to_candid_LeadType_n11(_uploadFile, _downloadFile, value.leadType),
        source: to_candid_LeadSource_n13(_uploadFile, _downloadFile, value.source),
        businessId: value.businessId
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: InvoiceStatus;
    date: Timestamp;
    subscriptionId: bigint;
    currency: string;
    amount: bigint;
}): {
    status: _InvoiceStatus;
    date: _Timestamp;
    subscriptionId: bigint;
    currency: string;
    amount: bigint;
} {
    return {
        status: to_candid_InvoiceStatus_n3(_uploadFile, _downloadFile, value.status),
        date: value.date,
        subscriptionId: value.subscriptionId,
        currency: value.currency,
        amount: value.amount
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: Timestamp;
    stripeSubscriptionId: string;
    userId: bigint;
    plan: Plan;
    startDate: Timestamp;
}): {
    endDate: _Timestamp;
    stripeSubscriptionId: string;
    userId: bigint;
    plan: _Plan;
    startDate: _Timestamp;
} {
    return {
        endDate: value.endDate,
        stripeSubscriptionId: value.stripeSubscriptionId,
        userId: value.userId,
        plan: to_candid_Plan_n25(_uploadFile, _downloadFile, value.plan),
        startDate: value.startDate
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadType): {
    call: null;
} | {
    inquiry: null;
} | {
    booking: null;
} {
    return value == LeadType.call ? {
        call: null
    } : value == LeadType.inquiry ? {
        inquiry: null
    } : value == LeadType.booking ? {
        booking: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadSource): {
    instagram: null;
} | {
    whatsapp: null;
} | {
    google: null;
} | {
    website: null;
} {
    return value == LeadSource.instagram ? {
        instagram: null
    } : value == LeadSource.whatsapp ? {
        whatsapp: null
    } : value == LeadSource.google ? {
        google: null
    } : value == LeadSource.website ? {
        website: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Plan): {
    growth: null;
} | {
    starter: null;
} | {
    premium: null;
} | {
    none: null;
} {
    return value == Plan.growth ? {
        growth: null
    } : value == Plan.starter ? {
        starter: null
    } : value == Plan.premium ? {
        premium: null
    } : value == Plan.none ? {
        none: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
} {
    return value == InvoiceStatus.pending ? {
        pending: null
    } : value == InvoiceStatus.paid ? {
        paid: null
    } : value == InvoiceStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    active: null;
} | {
    canceled: null;
} | {
    expired: null;
} {
    return value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.canceled ? {
        canceled: null
    } : value == SubscriptionStatus.expired ? {
        expired: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
